// SPDX-FileCopyrightText: Copyright (C) 2026 Aresta Climb Contributors
// SPDX-License-Identifier: MPL-2.0

edition = "2023";

package aresta;

import "google/protobuf/timestamp.proto";
import "croqui.proto";

// Representa um índice de croquis de escalada, apontando para onde recuperar o
// croqui inteiro.
message Indice {
    // Lista de croquis disponíveis.
    repeated ResumoCroqui croquis = 2;

    reserved 1;
    reserved url_base;
}

// Pré-computados para acesso rápido a estatísticas do croqui no índice.
message PrecomputadosResumoCroqui {
    // Soma total de escaladas em todos os picos do croqui.
    int32 total_escaladas = 1;

    // Número total de setores no croqui.
    int32 total_setores = 2;

    // Número total de grupos no croqui.
    int32 total_grupos = 3;

    int32 total_esportivas = 4;
    int32 total_moveis = 5;
    int32 total_boulders = 6;
    int32 total_multiplas_enfiadas = 7;
    int32 total_highlines = 8;

    // Tamanho total estimado em bytes para download offline do croqui (compilado.binarypb + imagens).
    int64 tamanho_download_bytes = 9;
}

// Resumo de um croqui que está disponível para o índice.
message ResumoCroqui {
    // Identificador único do croqui.
    string id = 1;

    // Nome do local do croqui.
    string nome = 2;

    // Descrição curta e em alto nível do local.
    string descricao = 3;

    // localização do arquivo relativo ao indice (i.e.
    // "br_mg_pedro_leopoldo_gruta_do_bau/compilado.binarypb").
    string caminho_relativo = 5;

    // Checksum SHA256 da última versão do croqui.
    // Se diferente do checksum da versão baixada, há atualizações.
    string checksum_sha256_croqui = 6;

    // Checksum SHA256 da última versão da thumbnail.
    // Se diferente do checksum da versão baixada, há atualizações.
    // A thumbnail *sempre* será localizada em "imagens/thumbnail.webp", relativa
    // à pasta onde está o croqui.binarypb.
    string checksum_sha256_thumbnail = 8;

    // Timestamp do último update.
    google.protobuf.Timestamp timestamp_update = 9;

    // Coordenada principal do croqui (baseada no estacionamento do primeiro pico).
    Coordenada localizacao = 10;

    // Estatísticas pré-computadas agregando todos os picos do croqui.
    PrecomputadosResumoCroqui precomputados = 11;

    reserved 4, 7;
    reserved data_update, nome_arquivo;
}